set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
"Set the historical logs of vim a proper dir
set undodir=~/.vim/undodir
set undofile 
set laststatus=2
"To change the buffer without saving it
set hidden
if !has('gui_running')
    set t_Co=256
endif

"Pathogen
call pathogen#infect() 
call pathogen#helptags()

let mapleader=" "
let g:lightline = {'colorscheme': 'wombat',}
filetype plugin indent on
colorscheme BlackSea


nnoremap <F5> :GundoToggle<CR>
"To group with ease from the command line
cmap ;\ \(\)<Left><Left>
nmap <Leader>e :!lua %<cr>
nmap <F3> :NERDTreeToggle<CR>
nmap <F4> :TagbarToggle<CR>
"Save with C-S
nmap <c-s> :update<CR>
vmap <c-s> <Esc><c-s>gv
imap <c-s> <Esc><c-s>

" Enable built-in matchit plugin
runtime macros/matchit.vim
nmap <Leader>m :!make <cr>
nmap <Leader>r :!./% <cr>

" to change the macro storage location use the following
let marvim_store='/home/charly/.vim/.macros'
let marvim_find_key = '<Leader>1' " busca macro Space+F2
let marvim_store_key = '<Leader>0'     " guardar macro Space+F3 
let marvim_register = 'c'       " change used register from 'q' to 'c'
let marvim_prefix = 1           " disable default syntax based prefix 

" Move to the next buffer
nmap <leader>l :bnext<CR>
"
" " Move to the previous buffer
nmap <leader>h :bprevious<CR>

" " Delete current buffer without delete window
" nmap <leader>k :bn|bd#<CR>
