set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
"Set the historical logs of vim a proper dir
set undodir=~/.vim/undodir
set undofile 
set laststatus=2
"To change the buffer without saving it
set hidden
if !has('gui_running')
    set t_Co=256
endif

"Pathogen
call pathogen#infect() 
call pathogen#helptags()

let mapleader=" "
let g:lightline = {'colorscheme': 'wombat',}
filetype plugin indent on
colorscheme BlackSea


nnoremap <F5> :GundoToggle<CR>
"To group with ease from the command line
cmap ;\ \(\)<Left><Left>
nmap <Leader>e :!lua %<cr>
nmap <F3> :NERDTreeToggle<CR>
nmap <F4> :TagbarToggle<CR>
"Save with C-S
nmap <c-s> :update<CR>
vmap <c-s> <Esc><c-s>gv
imap <c-s> <Esc><c-s>

" Enable built-in matchit plugin
 runtime macros/matchit.vim

