# ~/.bash_profile: executed by bash(1) for login shells.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/login.defs
#umask 022

# include .bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# set PATH so it includes user's private bins if them exists
if [ -d ~/Scripts ] ; then
     PATH+=":~/Scripts"
fi
if [ -d ~/.local/bin ] ; then
     PATH+=":~/.local/bin"
fi

export PATH
export MANPATH=$HOME/.local/share/man:$(manpath -gq)

