# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples


# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
#le pone color al grep siempre que no vaya empipado
export GREP_OPTIONS='--color=auto'
# Le pone el porcentaje less
export LESS='-m' # N (numero de lineas no me interesa,feo)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Corrige los errores en el cd 
shopt -s cdspell

# Los comandos multilinea los salva como un solo comando
shopt -s cmdhist

# No borrar el historial al crear uno nuevo
shopt -s histappend

# Permitir regexp en el macheado de la consola
#shopt -s extglob

# No hay necesidad de hacer hash -r cuando modificas directorios
# shopt -s checkhash


# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi


# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*)
    #PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    PROMPT_COMMAND=''
    ;;
rxvt*) # En el caso de una aterm le ponemos el numero de aterm lanzadas
    ACTUAL_WORKSPACE=$(wmctrl -ld | grep  \* | cut -d' ' -f 1)
    NATERM=$(wmctrl -lp | grep " $ACTUAL_WORKSPACE "[1-9] | ps -p `cut -d' ' -f 4` | grep -c [a]term)
    SITUACION=$ACTUAL_WORKSPACE.$NATERM
    PROMPT_COMMAND='history -a;echo -en "\033];Aterm $SITUACION\007"'
    ;;
*)
    ;;
esac

# Comment in the above and uncomment this below for a color prompt
#PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\][\[\033[00m\]\[\033[01;32m\]\u($SITUACION)->\033[00m\]\[\033[01;34m\]\w]\n>\[\033[00m\]'
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\][\[\033[00m\]\[\033[01;32m\]\u($SITUACION)->\[\033[00m\]\[\033[01;34m\]\w]\n>\[\033[00m\]'


# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto -CF'
fi

# Interesante, puedo ir a cualquier directorio de casita desde cualquier sitio, peligroso
# CDPATH=~
#EDITOR=vim  # update-alternatives --all  era la solucion
HISTSIZE=50000
HISTFILESIZE=50000
HISTFILE=~/.bash_historys/history_$SITUACION

# Hace algo de  autocomplete que no se lo que es
bind -m vi-insert "\C-p":dynamic-complete-history
bind -m vi-insert "\C-n":menu-complete

# ctrl l hace un clear como en el emacs mode
bind -m vi-insert "\C-l":clear-screen

#Para que autocomplete tambien !$,!*,!!,!cat ... despues de un space ... :)
bind Space:magic-space

# Ponemos mis scripts y el libreoffice
if [ -d ~/Scripts ] ; then
      PATH=~/.local/bin/:~/Scripts:/usr/NX/bin:/opt/eclipse:/opt/libreoffice3.6/program/:$PATH
fi

. ~/Scripts/z.sh

ver(){
[ -z "$1" ] && return
mplayer-masvolumen "$1" < /dev/null &> /dev/null &
read -p "¿Borrarlo (s/n)?:" res && [ $res == "s" ] && rm "$1"
}

#Para lua
#export LUA_PATH='./?.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib/lua/5.1/?.lua;/usr/lib/lua/5.1/?/init.lua; ~/.config/awesome/?.lua;~/.config/awesome/lib/?.lua;~/.config/awesome/pomodoroTasks/?.lua;~/.config/awesome/rc/?.lua;~/.config/awesome/scratch/?.lua;/usr/share/awesome/lib/?.lua;/usr/share/awesome/lib/awful/?.lua;/usr/share/awesome/lib/awful/layout/?.lua;/usr/share/awesome/lib/awful/layout/suit/?.lua;/usr/share/awesome/lib/awful/mouse/?.lua;/usr/share/awesome/lib/awful/widget/?.lua;/usr/share/awesome/lib/gears/?.lua;/usr/share/awesome/lib/menubar/?.lua;/usr/share/awesome/lib/vicious/?.lua;/usr/share/awesome/lib/vicious/contrib/?.lua;/usr/share/awesome/lib/vicious/widgets/?.lua;/usr/share/awesome/lib/wibox/?.lua;/usr/share/awesome/lib/wibox/layout/?.lua;/usr/share/awesome/lib/wibox/widget/?.lua;/usr/share/awesome/themes/default/?.lua;/usr/share/awesome/themes/sky/?.lua;/usr/share/awesome/themes/zenburn/?.lua;'

#Mode vi
set -o vi
